cc_binary(
    name = "example_simple",
    srcs = [
        "main.cc",
    ],
     tags = [
        "examples",
        "otlp",
        "otlp_http",
    ],
    deps = [
        "//api",
        "//examples/common/foo_library:common_foo_library",
        "//exporters/otlp:otlp_http_exporter",
    ],
)
